In [1]:
# Library Setting

# 예측에 필요한 라이브러리를 설정합니다.

import numpy as np
import pandas as pd
from tensorflow import keras
from keras.models import model_from_json
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.

In [2]:
# Load prediction model.
# There are two models, Choose one and load.
# 1. PGIS_Prediction_Model_W5.h5
# 2. PGIS_ESL_Prediction_Model.h5
# For more information of these models, refer to 'Introduction' folder.

# 학습 모델을 불러옵니다.
# 두 가지 학습 모델이 있습니다. 하나를 선택하시고 파일명과 함께 불러옵니다.
# 1. PGIS_Prediction_Model_W5.h5
# 2. PGIS_ESL_Prediction_Model.h5
# 학습 모델의 세부 정보는 Introduction 폴더에 있습니다.

model = keras.models.load_model("PGIS_Prediction_Model_W5.h5")

In [3]:
# Load csv file.
# Use 'PREDICTION_FORMAT.csv' file to predict.
# Please refer to 'PREDICTION_FORMAT_EXAMPLE.csv' to make custom csv file.

# csv 파일을 불러옵니다.
# 폴더에 있는'PREDICTION_FORMAT.csv' 파일을 사용합니다.
# 'PREDICTION_FORMAT_EXAMPLE.csv' 파일을 참고하여 예측할 경기의 csv 파일을 생성해야 합니다.

df_pre_test = pd.read_csv('PREDICTION_FORMAT_EXAMPLE.csv', header=0)
df_pre_test = df_pre_test.dropna()

In [4]:
# Prediction
# 예측을 진행합니다.

dataset_test = df_pre_test.values
team = dataset_test[:,0]
X_prediction = dataset_test[:,1:3]
Y_Prediction = model.predict(X_prediction.astype(np.float32))
result_all = []

for i in range(16):
    team_result = []
    team_name = team[i]
    prediction = Y_Prediction[i]   
    team_result.append((16-float(np.argmax(prediction)+1))+float(np.max(prediction)))
    team_result.append(team_name)
    result_all.append(team_result) 

result_all.sort(reverse=True)

final_prediction_rank = []
final_prediction_team_name = []
for i in range(len(result_all)):
        final_prediction_rank.append(i+1)
        final_prediction_team_name.append(result_all[i][1])
final_prediction = pd.DataFrame({"RANK":final_prediction_rank, "TEAM":final_prediction_team_name})

#final_prediction = final_prediction.set_index('RANK')
final_prediction

    RANK  TEAM
0      1   STK
1      2    SQ
2      3  FAZE
3      4  IFTY
4      5   GEN
5      6   ZEN
6      7   BRU
7      8   MCG
8      9    T1
9     10  TIAN
10    11   4AM
11    12  OATH
12    13   DXG
13    14    AF
14    15   DAY
15    16    TL